
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: CHC Research Log
  繁中: CHC-研究日誌
email: ccha97u@gmail.com
description:
  en: "Machine Learning and Autunomous Dirivng realted topics"
  繁中: "以機器學習以及自動駕駛為主的相關主題的技術日誌"
index:
  en: index.html
  繁中: index_tw.html
feed:
  en: /feed.xml
  繁中: /feed_tw.xml
url: "" # the base hostname & protocol for your site
linkedin_username: ccha97u
github_username:  GBJim

# Build settings
markdown: kramdown
