
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: CHC Research Log
  繁中: CHC-研究日誌
email: ccha97u@gmail.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  繁中: 歡迎來到這裡
index:
  en: index.html
  繁中: index_tw.html
feed:
  en: /feed.xml
  繁中: /feed_tw.xml
url: "" # the base hostname & protocol for your site
twitter_username: GBJim
github_username:  GBJim

# Build settings
markdown: kramdown
